name: Build resume
description: Build all resume assets
runs:
  using: composite

  steps:
    - uses: marocchino/tool-versions-action@v1.2.0
      id: versions

    - uses: earthly/actions-setup@v1
      with:
        version: ${{ steps.versions.outputs.earthly }}

    - shell: sh
      run: earthly +all --filename="Joe Lombrozo"
