# This is a basic workflow to help you get started with Actions

name: Compile resume

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Compile resume
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v2

      - name: compile assets
        env:
          WKHTML_VERSION: 0.12.6-1
        run: |
          sudo apt update
          sudo apt install -y fontconfig make pandoc xfonts-75dpi xfonts-base xvfb
          sudo wget https://github.com/wkhtmltopdf/packaging/releases/download/${WKHTML_VERSION}/wkhtmltox_${WKHTML_VERSION}.bionic_amd64.deb
          sudo dpkg -i wkhtmltox${WKHTML_VERSION}.bionic_amd64.deb
          make all

      - name: upload artifacts
        uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
