name: Compile and release resume

on:
  push:
    tags: ['*']

jobs:
  build:
    name: Compile and deploy resume

    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/build-assets

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: ./dist/*
          fail_on_unmatched_files: true
