name: Compile and release resume

on:
  push:
    tags: ['*']

jobs:
  build:
    name: Compile and deploy resume

    runs-on: self-hosted

    container:
      image: ubuntu:22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: wistia/parse-tool-versions@v2.0.0

      - uses: earthly/actions-setup@v1
        with:
          version: ${{ env.EARTHLY_TOOL_VERSION }}

      - name: compile assets
        env:
          WKHTML_VERSION: 0.12.6-1
        run: |
          apt update
          apt install make
          make install
          make all

      - name: Deploy assets to release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

      - name: Upload pdf
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/resume.pdf
          asset_name: Joe Lombrozo's Resume.pdf
          asset_content_type: application/pdf

      - name: Upload docx
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/resume.docx
          asset_name: Joe Lombrozo's Resume.docx
          asset_content_type: application/vnd.openxmlformats-officedocument.wordprocessingml.document
